apiVersion: v1
kind: Service
metadata:
  name: nexus
  namespace: nexus
spec:
  ports:
    - name: nexus-ui
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/instance: nexus
    app.kubernetes.io/name: nexus-repository-manager
  type: ClusterIP
