---
- name: Set node affinity
  hosts: localhost
  vars_files:
    - cluster.yaml # Replace with the name of your YAML file containing the specs
  tasks:
    - name: Label nodes with round-robin proxmox affinity
      become: yes
      command: >
        kubectl label nodes k3s-agent-{{ item.split('.') | last }} topology.kubernetes.io/zone={{ proxmox.zone }}-{{ (proxmox.ips[idx % proxmox.ips|length]|split('.')) | last }} --overwrite
      loop: "{{ agents.ips }}"
      loop_control:
        index_var: idx
      delegate_to: "{{ masters.ips[0] }}"
