---
- name: Set node affinity
  gather_facts: no
  hosts: localhost
  vars_files:
    - cluster.yaml # Replace with the name of your YAML file containing the specs
  tasks:
    - name: Set node affinity
      include_tasks: playbooks/node-affinity.yaml
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
      vars:
        current_vm: "{{ vm }}"
