---
- name: Destroy VMs on Proxmox
  gather_facts: no
  hosts: localhost
  vars_files:
    - cluster.yaml # Replace with the name of your YAML file containing the specs
  tasks:
    - name: Stop vm
      include_tasks: playbooks/qm-stop.yaml
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
      vars:
        current_vm: "{{ vm }}"
    - name: Destroy vm
      include_tasks: playbooks/qm-destroy.yaml
      loop: "{{ vms }}"
      loop_control:
        loop_var: vm
      vars:
        current_vm: "{{ vm }}"
