---
- name: Create VMs on Proxmox
  hosts: localhost
  vars_files:
    - cluster.yaml  # Your YAML file containing the specs
  tasks:
    - name: Download the script
      get_url:
        force: yes
        url: "https://raw.githubusercontent.com/MindMatrix/k3s-setup/main/create-vm.sh"
        dest: "/tmp/create-vm.sh"
        mode: "0777"
      delegate_to: "{{ item.ip }}"
      loop: "{{ config }}"

    - name: Create master VMs
      become: yes
      become_user: root
      command: >
        /tmp/create-vm.sh "k3s-master-{{ ip.split('.') | last }}" "{{ ip.split('.') | last }}" "{{ ip }}/24" "{{ gateway }}"
        "{{ masters.specs | selectattr('name', 'equalto', 'master') | map(attribute='ram') | first }}"
        "{{ masters.specs | selectattr('name', 'equalto', 'master') | map(attribute='cpus') | first }}"
        "{{ masters.specs | selectattr('name', 'equalto', 'master') | map(attribute='cores') | first }}"
        "{{ masters.specs | selectattr('name', 'equalto', 'master') | map(attribute='hdd') | first }}G" "{{ ansible_user }}"
      loop: "{{ item.masters }}"
      delegate_to: "{{ item.ip }}"
      loop: "{{ config }}"

    - name: Create agent VMs
      become: yes
      become_user: root
      command: >
        /tmp/create-vm.sh "k3s-agent-{{ ip.split('.') | last }}" "{{ ip.split('.') | last }}" "{{ ip }}/24" "{{ gateway }}"
        "{{ masters.specs | selectattr('name', 'equalto', 'agent') | map(attribute='ram') | first }}"
        "{{ masters.specs | selectattr('name', 'equalto', 'agent') | map(attribute='cpus') | first }}"
        "{{ masters.specs | selectattr('name', 'equalto', 'agent') | map(attribute='cores') | first }}"
        "{{ masters.specs | selectattr('name', 'equalto', 'agent') | map(attribute='hdd') | first }}G" "{{ ansible_user }}"
      loop: "{{ item.agents }}"
      delegate_to: "{{ item.ip }}"
      loop: "{{ config }}"
