- name: Iterate through VMs
  hosts: localhost
  gather_facts: false
  vars_files:
    - cluster.yaml
  tasks:
    - name: Download the script
      get_url:
        force: yes
        url: "https://raw.githubusercontent.com/MindMatrix/k3s-setup/main/create-vm.sh"
        dest: "/tmp/create-vm.sh"
        mode: "0777"
      delegate_to: "{{ item.ip }}"
      loop: "{{ config }}"
    - name: Create vms
      include_tasks: playbooks/create-vm.yaml
      loop: "{{ config }}"
      loop_control:
        loop_var: vm
      vars:
        current_vm: "{{ vm }}"
