---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gladeos-dev
  namespace: default
spec:
  secretName: gladeos-dev-staging-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.gladeos.dev"
  dnsNames:
    - "*.gladeos.dev"
