- name: reboot
  hosts:
    - master
    - node
  gather_facts: yes
  tasks:
    - name: Reboot the nodes (and Wait upto 5 mins max)
      become: true
      community.general.shutdown:
        delay: 0
