---
- name: Node affinity
  become: yes
  become_user: root
  command: >
    kubectl label nodes {{ agent_nodes_str }} topology.kubernetes.io/zone={{ current_vm.zone }}-{{ (current_vm.ip.split('.')) | last }} --overwrite
  loop: "{{ current_vm.masters }}"
  loop_control:
    loop_var: master_ip
  vars:
    agent_nodes_str: "{{ current_vm.agents | map('split', '.') | map('last') | map('regex_replace', '^(.*)$', 'k3s-agent-\\1') | join(' ') }}"
  delegate_to: "{{ master_ip }}"
