---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: <github_email>
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - selector: {}
        dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-token-secret
              key: access-token
